sonar.projectName=Booking API Integration Tests
sonar.sources=.
sonar.tests=test
sonar.test.inclusions=test/restful_booker.spec.ts
sonar.exclusions=node_modules/**,output/**,coverage/**,test/**
sonar.sourceEncoding=UTF-8
